### ISSUE TITLE
Package directory structure

### ISSUE THREAD

**Issue by ghost** [jossef/material-design-icons-iconfont#10]
Hi
Thank you for this package.

I think directory `dist` for sass files is not suitable and we can create a new directory named `css` for that sass file and later maybe less or stylus files.

Regards.

**Comment by jossef** [comment]
@sharifzadesina 

sorry for the late response, 
I'll move this file into a new dir as you suggest

**Comment by jossef** [comment]
fixed in 4.0.1 release
thanks!
