### ISSUE TITLE
Ballot Icon

### ISSUE THREAD

**Issue by sayhitoarvind** [jossef/material-design-icons-iconfont#16]
Hi, 
I just noticed that the ballot Icon seems broken. thought I should report it as a bug. 
Thanks

**Comment by jossef** [comment]
working in 4.0.1
https://jossef.github.io/material-design-icons-iconfont/

![image](https://user-images.githubusercontent.com/1287098/47607590-a5351080-da2a-11e8-81ad-d56a34ea9fff.png)
