### ISSUE TITLE
arrow_back_ios and arrow_forward_ios are missing.

### ISSUE THREAD

**Issue by cairin** [jossef/material-design-icons-iconfont#17]
This is in v3.0.3.

**Comment by jossef** [comment]
working in 4.0.1
https://jossef.github.io/material-design-icons-iconfont/

![image](https://user-images.githubusercontent.com/1287098/47607580-8d5d8c80-da2a-11e8-9cf8-91b90f78b221.png)

**Comment by cairin** [comment]
I can't use 4.0.1 because then I don't have access to content_copy, or any of the other older icons.

**Comment by jossef** [comment]
@cairinmichie 
is there a `content_copy` icon in the official https://material.io/tools/icons gallery? can't find it there

**Comment by javiholcman** [comment]
I am trying to use the .ttf into my ios app, but I can't find the arrow_back_ios icon. Where is it?
