### ISSUE TITLE
Is it out-of-date?

### ISSUE THREAD

**Issue by th0th** [jossef/material-design-icons-iconfont#2]
I tried to use "bubble_chart" icon and I got an empty icon. I can use that icon when I use the CSS file from Google (https://fonts.googleapis.com/icon?family=Material+Icons).

I thought it may be that "bubble_chart" icon is newly added and this repository hasn't been updated since? If so, can you please update?

**Comment by timfish** [comment]
Add [this PR](https://github.com/jossef/material-design-icons-iconfont/pull/3) to update to the latest icons...
