### ISSUE TITLE
missing codes in _variables.scss

### ISSUE THREAD

**Issue by Dariuosh** [jossef/material-design-icons-iconfont#27]
missing 
`how_to_vote` and `how_to_reg`

**Comment by jossef** [comment]
hmmm are you sure?

![image](https://user-images.githubusercontent.com/1287098/50305229-dcf48d80-049a-11e9-8310-f843186dd7e5.png)

**Comment by Dariuosh** [comment]
Maybe it's my wrong but I can't find in the `_variables.scss` file

![image](https://user-images.githubusercontent.com/3775035/50366879-9f266080-0591-11e9-82cf-e53bc798f8c7.png)

**Comment by jossef** [comment]
@Dariuosh 
got ya, will maintain `_variables.scss` to match the fonticons

**Comment by jossef** [comment]
WIP. will scrape these mappings from the compiled font.

https://stackoverflow.com/questions/54721774/extracting-ttf-font-ligature-mappings
https://github.com/foliojs/fontkit/issues/187

**Comment by ruant** [comment]
arrow_right is missing too.
Have you gotten the scrape implemented? 😃

**Comment by jossef** [comment]
@ruant 

yep, I've gotten progress with this, hope to publish a version very soon
sorry for the delay, I'm doing this on my spare time (i'm on this right now while riding the bus!)

**Comment by mptyspace** [comment]
Missing power_off too
