### ISSUE TITLE
Missing Icon 'contact_support'

### ISSUE THREAD

**Issue by fazulk** [jossef/material-design-icons-iconfont#28]
Looks like 'contact_support' is missing..

**Comment by jossef** [comment]
are you sure?

![image](https://user-images.githubusercontent.com/1287098/50570489-2cd62d00-0d96-11e9-9e18-38b4ccaf2dbb.png)

**Comment by jossef** [comment]
closing this, assuming related to https://github.com/jossef/material-design-icons-iconfont/issues/27
