### ISSUE TITLE
Ability to see codepoints from Demo Page

### ISSUE THREAD

**Issue by webleaf** [jossef/material-design-icons-iconfont#29]
There are environments where we can specify symbols only by hex code. It will be very useful if we could see codepoint right away from Demo Page.
I'm talking about such codepoints: https://github.com/google/material-design-icons/blob/master/iconfont/codepoints

**Comment by jossef** [comment]
sounds great, would you be able to submit a Pull Request on the `gh-pages` branch?

**Comment by ljani** [comment]
Also publishing a machine readable codepoints file is important for some environments. For example developers/users are able to use the icon names, which are then processed into codepoints in HTML to ensure legacy browser compatibility.
