### ISSUE TITLE
file_copy icon shows as large empty space

### ISSUE THREAD

**Issue by dannyb21892** [jossef/material-design-icons-iconfont#31]
![icon issue](https://user-images.githubusercontent.com/3780350/51131325-66c71a80-17fd-11e9-9c17-2191f40b5731.png)
 Appears like this, both from the original google icons, and this repo.

**Comment by jossef** [comment]
Thanks for reporting the issue, 

What version are you using?
I need your help reproducing the issue, I'm getting the icon as expected with 

```
<i class="material-icons">file_copy</i>
```
![image](https://user-images.githubusercontent.com/1287098/51207695-3de57900-1914-11e9-9bd7-bd236a787dd7.png)

**Comment by jossef** [comment]
closing this, assuming related to https://github.com/jossef/material-design-icons-iconfont/issues/27
