### ISSUE TITLE
Remove local() from CSS

### ISSUE THREAD

**Issue by The-MAZZTer** [jossef/material-design-icons-iconfont#32]
I got bit with this and it took me entirely too long to figure it out. The web font should be preferred over a locally installed one due to older versions of the font missing some glyphs.

**Comment by jossef** [comment]
removing the `local()` is a breaking change for IE users;
https://stackoverflow.com/a/22835957/3191896

**Comment by jossef** [comment]
I'm gonna use a generic `local('☺')` instead
https://stackoverflow.com/a/22835957/3191896
