### ISSUE TITLE
Lighthouse audit suggests font be loading using <link rel=preload>

### ISSUE THREAD

**Issue by bdiz** [jossef/material-design-icons-iconfont#38]
Lighthouse suggest performance improvement where font should be indicated as preload.

![image](https://user-images.githubusercontent.com/944954/53735813-95e92800-3e4d-11e9-99ab-cfe5fb217ec1.png)

I am unsure how to change the iconfont to be preloaded?

**Comment by DeutscheBundesstiftungUmwelt** [comment]
Me too ;) Any suggestions?

**Comment by bdiz** [comment]
I'm no expert at @vue/preload-webpack-plugin, but this is what I ended up with in my vue.config.js:

```javascript
// ...
module.exports = {
  // ...
  chainWebpack: (config) => {
    // ...
    const isLegacyBundle = process.env.VUE_CLI_MODERN_MODE && !process.env.VUE_CLI_MODERN_BUILD;
    if (!isLegacyBundle) {
      config.plugin("preload").tap(() => {
        return [{
          rel: "preload",
          include: "allAssets",
          fileWhitelist: [/.*\.css/, /.*\.js/, /.*\.woff2$/],
          fileBlacklist: [/\.map$/, /hot-update\.js$/]
        }];
      });
    }
    // ...
  }
};
```

Seems to have fixed the issue so far.

**Comment by Wlada** [comment]
Any solution with Angular CLI ?
