### ISSUE TITLE
Rounded Icons

### ISSUE THREAD

**Issue by Venipa** [jossef/material-design-icons-iconfont#41]
Could you add support for rounded icons?
https://material.io/tools/icons/?icon=done&style=round

**Comment by Venipa** [comment]
Renamed the source where you'r getting it from, tho now some icons are misplaced
![](https://i.mavis.moe/f/s1INuy3yMQ/2019-04-05-13-32-01.png)

**Comment by rafamel** [comment]
It would be great if all variations were supported (regular/filled, outlined, rounded, two-tone and sharp).

**Comment by jossef** [comment]
WIP to support this
https://github.com/material-icons/build/issues/1

**Comment by rsivan** [comment]
I am confused, is there support for outlined etc in 6.0.1?

**Comment by jossef** [comment]
hey, not yet. sorry for the slow progress

**Comment by jossef** [comment]
dup #33
