### ISSUE TITLE
Material icon font not working with angular 8

### ISSUE THREAD

**Issue by millerlight** [jossef/material-design-icons-iconfont#44]
The paths in material-design-icons.scss
are not correct for the new specifications.

CssSyntaxError:  
Can't resolve './fonts/MaterialIcons-Regular.eot'
 Can't resolve './fonts/MaterialIcons-Regular.ttf' 
Can't resolve './fonts/MaterialIcons-Regular.woff'
...

How to fix: 
copy the font folder from the node package relative to the path of the file in which you import the scss for the material icons.

**Comment by VictorGerritsen** [comment]
How are you including the styles? 

I am using Angular 8 and do not seem to have this issue, although i include the styles from the `dist` folder instead of the `src`.

```
@import "~material-design-icons-iconfont/dist/fonts/material-icons.css";
```

**Comment by lnu** [comment]
replace `$material-design-icons-font-path` by `$material-design-icons-font-directory-path`
the readme has been [updated](https://github.com/jossef/material-design-icons-iconfont/commit/25db3c0d5825bd09237fad6e4af750b80b7c4fd6#diff-04c6e90faac2675aa89e2176d2eec7d8) last month.

**Comment by jossef** [comment]
@millerlight - @lnu is correct, the path variable was renamed (maybe should have bumped a major version now when I'm thinking of this)

sorry about the trouble

**Comment by vazricv** [comment]
I have this issue and its a new project and still doesnt work with new changes applied

X [ERROR] Could not resolve "../node_modules/material-design-icons-iconfont/dist/fonts/MaterialIcons-Regular.ttf" [plugin angular-css-resource]

    src/styles.scss:8:357:
      8 │ ...off"), url("../node_modules/material-design-icons-iconfont/src||...
