### ISSUE TITLE
Prebuilt file without the codepoint list

### ISSUE THREAD

**Issue by stof** [jossef/material-design-icons-iconfont#55]
When following the official way to use material-design-icons, we will not need the classes generated for each codepoint. And these make up the most part of the CSS file.

The scss file exposes a `$material-design-icons-class-icons-generate-codepoints` variable to disable the generation of all these classes. It would be great if the npm package could ship 2 CSS files instead of 1:

- one with the feature turned on (as done today)
- one with the feature turned off, for projects not using the codepoint classes but following the official material-design-icons pattern.

**Comment by henrijs** [comment]
$material-design-icons-class-icons-generate-codepoints: false;

**Comment by jossef** [comment]
fixed in https://github.com/jossef/material-design-icons-iconfont/releases/tag/v6.4.0
![image](https://user-images.githubusercontent.com/1287098/154819775-07159975-5892-4688-903f-7baecb791615.png)
