### ISSUE TITLE
Is there demo page for different versions?

### ISSUE THREAD

**Issue by jackniu81** [jossef/material-design-icons-iconfont#60]
We use different version of this lib, and can not upgrade very frequently. Is there demo page for old versions?
This page only contains the latest: https://jossef.github.io/material-design-icons-iconfont/

**Comment by jossef** [comment]
thanks for reporting, currently no. I'll address this issue

**Comment by jossef** [comment]
as of today, the demo has been moved to the master branch 
this means you will be able to switch to another released tag and run locally 
```
npm run docs-dev
```
