### ISSUE TITLE
Replace "HA! Nothing found for "[icon name]"." text

### ISSUE THREAD

**Issue by lundmikkel** [jossef/material-design-icons-iconfont#62]
It's a super provocative text (especially together with the laughing smiley) that doesn't help the user. Users are very likely to hit the page when trying to guess the name of an icon. Mocking them when they didn't guess the magic icon name is unnecessary.

Just write something like "Couldn't find an icon for [icon name]" or something along those lines.

**Comment by jossef** [comment]
👍
