### ISSUE TITLE
Help with mixins, icons not showing

### ISSUE THREAD

**Issue by JorgeSibrian14** [jossef/material-design-icons-iconfont#63]
I'm usign laravel 6 that work with webpack, i do this imports on app.scss:
//material-icons
$material-design-icons-font-path: '~material-design-icons-iconfont/dist/fonts/';
@import '~material-design-icons-iconfont/src/material-design-icons';

And then i use this to put an icon in a button, just for trying:
![image](https://user-images.githubusercontent.com/56272944/82266605-5bbb5780-9927-11ea-8b93-d0058b8dc629.png)
I run: npm run dev(and i use too: npm run watch), and reload deleting cache from browser and i get this:
![image](https://user-images.githubusercontent.com/56272944/82266630-6ece2780-9927-11ea-8845-732237794b35.png)

The material icons when i use the span tag is working well.
![image](https://user-images.githubusercontent.com/56272944/82266662-80afca80-9927-11ea-9da7-bf047aec09bb.png)
But when i use the mixins that happens. Can you help me please?

**Comment by AsuScholar** [comment]
Getting the same issue here. <i> tag works but mixin does not.

**Comment by AsuScholar** [comment]
Had the same issue. Looks like you need to include **@extend .material-icons;** in your class.

Example:
```
.some-class {
   @extend .material-icons;
   @include material-icon('keyboard_arrow_right');
}
```
