### ISSUE TITLE
bower.json main files missing

### ISSUE THREAD

**Issue by tiberiuzuld** [jossef/material-design-icons-iconfont#7]
Hi,

Main files missing from bower.json. 
Example:
`"main": [
        "dist/fonts/material-icons.css",   
        "dist/fonts/MaterialIcons-Regular.eot",   
        "dist/fonts/MaterialIcons-Regular.woff2",   
        "dist/fonts/MaterialIcons-Regular.woff",   
        "dist/fonts/MaterialIcons-Regular.ttf"   
      ]`

I use this in combination with https://www.npmjs.com/package/gulp-main-bower-files 
to automate build process.

Another issue I had is that `/*# sourceMappingURL=material-design-icons.css.map */` in the `dist/material-design-icons.css` was interfering with https://www.npmjs.com/package/gulp-sourcemaps
I had to use the `dist/fonts/material-icons.css` file instead.

Thanks.

P.S. : thank you for this repo 👍

**Comment by jossef** [comment]
hey friend, could you please explain -

> ... was interfering with https://www.npmjs.com/package/gulp-sourcemaps

**Comment by tiberiuzuld** [comment]
gulp-sourcemaps was looking for the css map at 
/*# sourceMappingURL=material-design-icons.css.map */
and would not find it correctly and will throw error and stop.

**Comment by gregdymek** [comment]
hi,
when are you going to release that?
for now the library is not working with webpack dist,
regards

**Comment by jossef** [comment]
@gregdymek it's already released in https://github.com/jossef/material-design-icons-iconfont/releases/tag/3.0.2

can you add more details about what's not working?

**Comment by gregdymek** [comment]
I see there is empty main in package.json, also in 3.0.2 version
when I build my application under webpack it's saying material-design-icons-iconfont cannot be resolved,
when I changed main attribute to match the scss location it's working fine,
main section from package.json
regards

**Comment by gregdymek** [comment]
so would it be also possible to fix it package.json?

**Comment by jossef** [comment]
thanks @gregdymek. released 3.0.3 with a fix

**Comment by gregdymek** [comment]
great, thanks!
