### ISSUE TITLE
Changelog is missing for the 6.x release

### ISSUE THREAD

**Issue by stof** [jossef/material-design-icons-iconfont#70]
Bumping the major version implies that there might be BC breaks, so not having any readme looks weird to me.

**Comment by jossef** [comment]
the release notes are auto generated from the commit changes (via semantic-release) 
https://github.com/jossef/material-design-icons-iconfont/releases/tag/v6.1.0

![image](https://user-images.githubusercontent.com/1287098/93012464-52768a80-f5a9-11ea-9402-2e0c422327f4.png)



I did bumped the major. sorry if that confuses you
from now on the major will not bump unless there are breaking changes
