### ISSUE TITLE
Minified version is missing

### ISSUE THREAD

**Issue by jeserkin** [jossef/material-design-icons-iconfont#71]
I feel like there should be a minified version of css file as well. There is one for different frames. For example bootstrap comes with one as well.

**Comment by jeserkin** [comment]
@jossef is this repo still supported by you or no plans for the future?

**Comment by jossef** [comment]
fixed in https://github.com/jossef/material-design-icons-iconfont/releases/tag/v6.3.0
, + sorry for late reply
