### ISSUE TITLE
Allow to set path variables before loading fonts

### ISSUE THREAD

**Issue by jeserkin** [jossef/material-design-icons-iconfont#72]
At the moment having an issue, that I am serving my application from location different than root `/`, but fonts are being served from `/`.
Also no easy way to override path variable before fonts are loaded.

**Comment by jossef** [comment]
Are you using `scss`? if so - define `$material-design-icons-font-directory-path` before importing the library

```
$material-design-icons-font-directory-path: '~material-design-icons-iconfont/dist/fonts/';
@import '~material-design-icons-iconfont/src/material-design-icons';
```

**Comment by jeserkin** [comment]
Resolved
