### ISSUE TITLE
I can't find play_lesson icon

### ISSUE THREAD

**Issue by mrjelveh** [jossef/material-design-icons-iconfont#74]
I can't find **play_lesson** icon, please add it in your library.
[play_lesson icon](https://material.io/resources/icons/?search=play_lesson&icon=play_lesson&style=baseline)

![image](https://user-images.githubusercontent.com/10113321/107521340-ae305880-6bc7-11eb-96a6-d9cd75770946.png)

**Comment by odysseus654** [comment]
FWIW while you wait for an official response, I did check out the repo and did "npm install" and "npm run build" and found that I had updated files in the "dist" folder which does include play_lesson.

**Comment by agerbig** [comment]
The icon is available in Version 6.1.1.
