### ISSUE TITLE
The package.json "version" field contains "v" prefix

### ISSUE THREAD

**Issue by JeremyGrieshop** [jossef/material-design-icons-iconfont#75]
I believe it should just be a numeric (semantic) version identifier without the "v" prefix.  It's never caused problems in the past, but the latest NPM seems to be a little confused when you run `npm outdated`:

```
$ npm outdated
Package                         Current  Wanted   Latest  Location  
material-design-icons-iconfont   v6.1.0   6.1.0    6.1.0  node_modules/material-design-icons-iconfont 
```

**Comment by jossef** [comment]
fixed since 6.4.1 https://www.npmjs.com/package/material-design-icons-iconfont/v/6.4.1
