### ISSUE TITLE
"calendar_view_" icons missing

### ISSUE THREAD

**Issue by wlucha** [jossef/material-design-icons-iconfont#76]
The "calendar_view" icons are missing:
- "calendar_view_week"
- "calendar_view_month"
- "calendar_view_day"

![image](https://user-images.githubusercontent.com/7531596/122240360-0226b300-cec2-11eb-8f86-95bb78287e2c.png)
![image](https://user-images.githubusercontent.com/7531596/122240417-0ce14800-cec2-11eb-8146-5d00a32edb5c.png)

**Comment by agerbig** [comment]
The icons are available in Version 6.1.1.

**Comment by jossef** [comment]
fixed in [v6.2.0](https://github.com/jossef/material-design-icons-iconfont/releases/tag/v6.2.0)
