### ISSUE TITLE
"female","male" icons missing

### ISSUE THREAD

**Issue by lzw-leaf** [jossef/material-design-icons-iconfont#77]
![image](https://user-images.githubusercontent.com/42256828/132979837-928499f6-f294-4b4c-967e-63f53df6cd65.png)

**Comment by agerbig** [comment]
The icons are available in Version 6.1.1.

**Comment by jossef** [comment]
fixed in [v6.2.0](https://github.com/jossef/material-design-icons-iconfont/releases/tag/v6.2.0)
