### ISSUE TITLE
package.json - "main" is blank and cause error in webpack

### ISSUE THREAD

**Issue by jossef** [jossef/material-design-icons-iconfont#8]
main should be 

```
  "main": "dist/material-design-icons.scss",
```

thanks to @gregdymek for reporting this issue

**Comment by thw0rted** [comment]
The `main` value in your comment above is correct, but the one in the `package.json` today is wrong.  By including `src/material-design-icons.scss` you wind up referencing relative paths that don't exist.  In webpack, this results in:

> Can't resolve './fonts/MaterialIcons-Regular.eot' in '.\node_modules\material-design-icons-iconfont\src'

I'm putting together a small PR to fix it.

**Comment by jossef** [comment]
Thanks, added to [v4.0.4](https://github.com/jossef/material-design-icons-iconfont/releases/tag/4.0.4)
