### ISSUE TITLE
NPM and Git mismatch

### ISSUE THREAD

**Issue by julianrutten** [jossef/material-design-icons-iconfont#85]
When I get the `6.1.1` version the `dist/material-design-icons.css` file does not include `restart_alt`.  
`cat node_modules/material-design-icons-iconfont/dist/material-design-icons.css | grep restart`
However in this repo it does:
https://github.com/jossef/material-design-icons-iconfont/blob/46e1847994507ffeb6bebd3a04cd12cd8020c449/dist/material-design-icons.css#L3030

Any ideas?

**Comment by jossef** [comment]
@julianrutten 
I've downloaded the tar.gz file from npm:
https://registry.npmjs.org/material-design-icons-iconfont/-/material-design-icons-iconfont-6.1.1.tgz

then, I extracted the files and open the `dist/material-design-icons.css` file. I don't see it's missing
![image](https://user-images.githubusercontent.com/1287098/152959668-05649d72-9294-4251-8ce6-1a100367e87d.png)
