### ISSUE TITLE
your fork is behind master?

### ISSUE THREAD

**Issue by jfix** [jossef/material-design-icons-iconfont#9]
Hello, great initiative to make just the iconfont available as an npm module. I just noticed that this repo seems to be behind the master. I don't know whether that includes any icon updates, but I'm hesitant to use it if new icons might not be available. Have you planned in catching up with the master? Thanks!

**Comment by jossef** [comment]
@jfix 

Yes, I forked from their master branch. However, I update the release artifacts manually from https://github.com/google/material-design-icons/releases

![image](https://user-images.githubusercontent.com/1287098/29067103-0cee3b84-7c3a-11e7-9313-4617a55e8bb9.png)
- last release was from 2016

therefore the stats (`x commits behined master`) are misleading (unless you seek for unstable WIP lying on their master branch - is that the case?)

**Comment by jfix** [comment]
Hi @jossef, you're right, my bad. FYI, I'm using your npm module happily, no problems with missing icons whatsoever!
